### ISSUE TITLE
How is authorization handled?

### ISSUE THREAD

**Issue by piotr-dobrogost** [mattikus/pygist#4]
There's no information in readme on how to authorize pygist to my gist account.

**Comment by mattikus** [comment]
Hey @piotr-dobrogost, sadly this project has been abandoned for quite some time and I haven't ever updated to use the new github API and support an oauth flow for authorization.

I'm hoping to one day pick this back up and update it, but I suggest looking into some other options out there in the meantime.

**Comment by nealmcb** [comment]
See #3
